#!/bin/bash

set -e

RULESET="
  add table t
  add chain t c { type filter hook input priority mangle; }
  add rule t c iif lo ct mark & 0xff 0x10 meta mark set ct mark >> 8
"

$NFT -f - <<< "$RULESET"
