#!/bin/bash

set -e

ruleset_file=$(mktemp)

trap 'rm -f "$ruleset_file"' EXIT

{
	echo 'define big_set = {'
	for ((i = 1; i < 255; i++)); do
		for ((j = 1; j < 255; j++)); do
			echo "10.0.$i.$j,"
		done
	done
	echo '10.1.0.0/24 }'
} >"$ruleset_file"

cat >>"$ruleset_file" <<\EOF
table inet test68_table {
	set test68_set {
		type ipv4_addr
		flags interval
		elements = { $big_set }
	}
}
EOF

( ulimit -s 400 && $NFT -f "$ruleset_file" )
