#!/bin/bash

set -e

RULESET="table ip x {
	chain y {
		ip daddr 192.168.0.1 counter accept
		ip daddr 192.168.0.2 counter accept
		ip daddr 192.168.0.3 counter accept
	}
}"

$NFT -o -f - <<< $RULESET
