#!/bin/bash

set -e

RULESET="table ip x {
	chain y {
		ip saddr 1.1.1.1 ip daddr 2.2.2.2 accept
		ip saddr 2.2.2.2 ip daddr 3.3.3.3 drop
		ip saddr 4.4.4.4 ip daddr 5.5.5.5 accept
	}
}"

$NFT -o -f - <<< $RULESET
