#!/bin/bash

set -e

# Input file contains rules with anon sets that contain
# one element, plus extra rule with two elements (that should be
# left alone).

# Dump file has the simplified rules where anon sets have been
# replaced by equality tests where possible.
dumpfile=$(dirname $0)/dumps/$(basename $0).nft

$NFT -f "$dumpfile".input
